version: '3.8'

services:
  # --- SINCELEJO NODE ---
  db_sincelejo:
    image: postgres:15-alpine
    container_name: db_sincelejo
    networks: [ clinica_net ]
    environment:
      - POSTGRES_USER=admin_clinica
      - POSTGRES_PASSWORD=password_seguro
      - POSTGRES_DB=historia_clinica_global
    volumes: 
      - pg_global_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_clinica -d historia_clinica_global"]
      interval: 5s
      timeout: 5s
      retries: 5

  app_sincelejo:
    build: .
    container_name: app_sincelejo
    ports: [ "3001:3000" ]
    networks: [ clinica_net ]
    environment:
      - SEDE_ACTUAL=Sincelejo
      - DB_HOST=db_sincelejo
      - KAFKA_BROKER=kafka:9092
    depends_on:
      db_sincelejo: { condition: service_healthy }
      kafka: { condition: service_healthy }

  # --- BOGOTA NODE ---
  db_bogota:
    image: postgres:15-alpine
    container_name: db_bogota
    networks: [ clinica_net ]
    environment:
      - POSTGRES_USER=admin_clinica
      - POSTGRES_PASSWORD=password_seguro
      - POSTGRES_DB=historia_clinica_global
    volumes: 
      - pg_bogota_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_clinica -d historia_clinica_global"]
      interval: 5s
      timeout: 5s
      retries: 5

  app_bogota:
    build: .
    container_name: app_bogota
    ports: [ "3002:3000" ]
    networks: [ clinica_net ]
    environment:
      - SEDE_ACTUAL=Bogota
      - DB_HOST=db_bogota
      - KAFKA_BROKER=kafka:9092
    depends_on:
      db_bogota: { condition: service_healthy }
      kafka: { condition: service_healthy }

  # --- MEDELLIN NODE ---
  db_medellin:
    image: postgres:15-alpine
    container_name: db_medellin
    networks: [ clinica_net ]
    environment:
      - POSTGRES_USER=admin_clinica
      - POSTGRES_PASSWORD=password_seguro
      - POSTGRES_DB=historia_clinica_global
    volumes: 
      - pg_medellin_data:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin_clinica -d historia_clinica_global"]
      interval: 5s
      timeout: 5s
      retries: 5

  app_medellin:
    build: .
    container_name: app_medellin
    ports: [ "3003:3000" ]
    networks: [ clinica_net ]
    environment:
      - SEDE_ACTUAL=Medellin
      - DB_HOST=db_medellin
      - KAFKA_BROKER=kafka:9092
    depends_on:
      db_medellin: { condition: service_healthy }
      kafka: { condition: service_healthy }

  # --- CENTRAL BUS (KAFKA) ---
  kafka:
    image: apache/kafka:3.8.0
    container_name: central_kafka
    ports: [ "9092:9092" ]
    networks: [ clinica_net ]
    environment:
      - KAFKA_NODE_ID=1
      - KAFKA_PROCESS_ROLES=broker,controller
      - KAFKA_LISTENERS=PLAINTEXT://:9092,CONTROLLER://:9093
      - KAFKA_ADVERTISED_LISTENERS=PLAINTEXT://kafka:9092
      - KAFKA_CONTROLLER_QUORUM_VOTERS=1@kafka:9093
      - KAFKA_CONTROLLER_LISTENER_NAMES=CONTROLLER
      - KAFKA_INTER_BROKER_LISTENER_NAME=PLAINTEXT
      - KAFKA_LISTENER_SECURITY_PROTOCOL_MAP=CONTROLLER:PLAINTEXT,PLAINTEXT:PLAINTEXT
      - KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR=1
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=true
    healthcheck:
      test: [ "CMD-SHELL", "kafka-topics.sh --bootstrap-server localhost:9092 --list || exit 0" ]
      interval: 10s
      timeout: 10s
      retries: 5

  # --- OBSERVABILITY (ITEM 5.3) ---
  prometheus:
    image: prom/prometheus:latest
    container_name: monitoreo_prom
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks: [ clinica_net ]

  grafana:
    image: grafana/grafana:latest
    container_name: monitoreo_grafana
    ports:
      - "3005:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin
    networks: [ clinica_net ]
    depends_on:
      - prometheus

networks:
  clinica_net:
    driver: bridge

volumes:
  pg_global_data:
  pg_bogota_data:
  pg_medellin_data:
